import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1779462317544 implements MigrationInterface {
    name = 'Migration1779462317544'

    public async up(queryRunner: QueryRunner): Promise<void> {
 
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS "public"`);
    await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS "setting"`);
    await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS "task_distribution"`);

        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);

        await queryRunner.query(`CREATE TABLE "setting"."organization" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "alternative_names" jsonb, "email" character varying NOT NULL, "phone" character varying NOT NULL, "address" character varying NOT NULL, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_c21e615583a3ebbb0977452afb0" UNIQUE ("name"), CONSTRAINT "UQ_5d06de67ef6ab02cbd938988bb1" UNIQUE ("email"), CONSTRAINT "PK_472c1f99a32def1b0abb219cd67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invitation_link_role_enum" AS ENUM('Contributor', 'Facilitator', 'Reviewer')`);
        await queryRunner.query(`CREATE TABLE "invitation_link" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid, "task_id" uuid, "expiry_date" TIMESTAMP NOT NULL, "max_invitations" integer, "current_invitations" integer NOT NULL DEFAULT '0', "role" "public"."invitation_link_role_enum", "organization_id" uuid, "created_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_63004f50fe26217b1321888c574" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."project_status_enum" AS ENUM('Active', 'InActive')`);
        await queryRunner.query(`CREATE TABLE "project" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "cover_image_url" character varying, "manager_id" uuid, "start_date" TIMESTAMP, "end_date" TIMESTAMP, "status" "public"."project_status_enum" NOT NULL DEFAULT 'Active', "is_archived" boolean NOT NULL DEFAULT false, "updated_by" character varying, "tags" text array, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying, CONSTRAINT "UQ_dedfea394088ed136ddadeee89c" UNIQUE ("name"), CONSTRAINT "PK_4d68b1358bb5b766d3e78f32f57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."task_type_task_type_enum" AS ENUM('audio-text', 'text-audio', 'text-text', 'image-text', 'image-audio')`);
        await queryRunner.query(`CREATE TABLE "task_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_type" "public"."task_type_task_type_enum" NOT NULL, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_adcb9dc6e3a93d5c7e20ce4bb30" UNIQUE ("task_type"), CONSTRAINT "PK_a0669bd34078f33604ec209dab1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "setting"."dialect" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "alternative_names" jsonb DEFAULT '[]', "description" character varying, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "language_id" uuid, "deletedAt" TIMESTAMP, CONSTRAINT "UQ_196e6fb4451958a75d6e8c1a836" UNIQUE ("name"), CONSTRAINT "PK_091d205f09398c89ac94c49f978" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "setting"."language" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "alternative_names" jsonb, "code" character varying, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_7df7d1e250ea2a416f078a631fb" UNIQUE ("name"), CONSTRAINT "UQ_465b3173cdddf0ac2d3fe73a33c" UNIQUE ("code"), CONSTRAINT "PK_cc0a99e710eb3733f6fb42b1d4c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_task_role_enum" AS ENUM('Contributor', 'Facilitator', 'Reviewer', 'QualityAssurance')`);
        await queryRunner.query(`CREATE TYPE "public"."user_task_status_enum" AS ENUM('Active', 'InActive', 'Flagged', 'Rejected', 'Pending')`);
        await queryRunner.query(`CREATE TABLE "user_task" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "has_done_task" boolean NOT NULL DEFAULT false, "task_id" uuid NOT NULL, "role" "public"."user_task_role_enum" NOT NULL, "status" "public"."user_task_status_enum" NOT NULL DEFAULT 'Active', "is_flagged" boolean NOT NULL DEFAULT false, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ea320dbd04b37ad98f9ff5033f6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_instruction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" uuid NOT NULL, "title" character varying NOT NULL, "content" text NOT NULL, "image_instruction_url" character varying, "video_instruction_url" character varying, "audio_instruction_url" character varying, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_01581ae3e9671770eda8de1c1b" UNIQUE ("task_id"), CONSTRAINT "PK_d632a3ccbfbbb8053119b96ff0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_payment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" uuid NOT NULL, "contributor_credit_per_microtask" integer NOT NULL, "reviewer_credit_per_microtask" integer NOT NULL, "status" character varying, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_0c32d331e470ebb15a1c98e48b" UNIQUE ("task_id"), CONSTRAINT "PK_bc31db495ba2049c69ea5820ca1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_requirement" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" uuid NOT NULL, "max_contributor_per_micro_task" integer, "max_contributor_per_facilitator" integer, "max_dataset_per_reviewer" integer DEFAULT '10', "max_reviewer_per_dataset" integer NOT NULL DEFAULT '1', "max_micro_task_per_contributor" integer, "minimum_seconds" integer, "maximum_seconds" integer, "minimum_characters_length" integer, "maximum_characters_length" integer, "batch" integer, "appriximate_time_per_batch" integer, "max_retry_per_task" integer, "is_dialect_specific" boolean NOT NULL DEFAULT false, "dialects" jsonb, "is_age_specific" boolean NOT NULL DEFAULT false, "age" jsonb, "is_sector_specific" boolean NOT NULL DEFAULT false, "sectors" text array, "is_gender_specific" boolean NOT NULL DEFAULT false, "gender" jsonb, "is_location_specific" boolean NOT NULL DEFAULT false, "locations" jsonb, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_62ec6ff566bc90aec40fccd9b3" UNIQUE ("task_id"), CONSTRAINT "PK_8da44a64284ada66482e47171e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "facilitator_contributor" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "facilitator_id" uuid NOT NULL, "contributor_id" uuid NOT NULL, "task_id" uuid NOT NULL, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9c6762197238466c6af76bcd14d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "qa_task_instruction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" uuid NOT NULL, "title" character varying NOT NULL, "content" text NOT NULL, "image_instruction_url" character varying, "video_instruction_url" character varying, "audio_instruction_url" character varying, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "reviewerTaskId" uuid, "qaTaskId" uuid, CONSTRAINT "REL_6bf4ff6fc0d3958861cddeb469" UNIQUE ("task_id"), CONSTRAINT "PK_31984766c6a8315a04832c187e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reviewer_task_instruction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" uuid NOT NULL, "title" character varying NOT NULL, "content" text NOT NULL, "image_instruction_url" character varying, "video_instruction_url" character varying, "audio_instruction_url" character varying, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "reviewerTaskId" uuid, "qaTaskId" uuid, CONSTRAINT "REL_bd4f85f249b2074d3790bfaa5e" UNIQUE ("task_id"), CONSTRAINT "PK_2adb6dd79b88f9f64e325803d78" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "is_public" boolean NOT NULL DEFAULT true, "require_contributor_test" boolean NOT NULL DEFAULT false, "is_closed" boolean NOT NULL DEFAULT false, "is_archived" boolean NOT NULL DEFAULT false, "distribution_started" boolean NOT NULL DEFAULT false, "contributor_completion_time_limit" integer, "reviewer_completion_time_limit" integer, "max_expected_no_of_contributors" integer, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "project_id" uuid NOT NULL, "task_type_id" uuid NOT NULL, "language_id" uuid NOT NULL, CONSTRAINT "PK_fb213f79ee45060ba925ecd576e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."micro_task_status_enum" AS ENUM('open', 'closed')`);
        await queryRunner.query(`CREATE TABLE "micro_task" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "is_test" boolean NOT NULL DEFAULT false, "instruction" text, "file_path" character varying, "text" text, "type" character varying, "category" character varying, "intent" character varying, "has_meet_target_dataset" integer, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "task_id" uuid NOT NULL, "status" "public"."micro_task_status_enum" NOT NULL DEFAULT 'open', "derived_from_microtask_id" uuid, "derived_from_dataset_id" uuid, CONSTRAINT "PK_9874f30adf010c98add311de714" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "setting"."rejection_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "alternative_names" jsonb, "description" character varying NOT NULL, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_a4292d95448bfcabcedf9cce370" UNIQUE ("name"), CONSTRAINT "PK_d73792e01fe911140d1fa894ab9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "setting"."flag_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "alternative_names" jsonb, "description" character varying NOT NULL, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_f09504271da4b00347c6758cd60" UNIQUE ("name"), CONSTRAINT "PK_8a5986319e4d52206d12babc17e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "flag_reason" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reason" character varying, "comment" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "data_set_id" uuid NOT NULL, "data_set_review_id" uuid, "flag_type_id" uuid NOT NULL, CONSTRAINT "PK_bd75143337ec0fd633fd5f68164" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "setting"."annotation_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "alternative_names" jsonb DEFAULT '[]', "description" character varying NOT NULL, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_d6f3759eb3ea2cd8c2f613c2fe4" UNIQUE ("name"), CONSTRAINT "PK_2228dabb5f327a4e6b3d9d7b4c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "setting"."annotation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "alternative_names" jsonb, "description" character varying NOT NULL, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "annotation_type_id" uuid, CONSTRAINT "UQ_490a51dbf5298ead7cb0d391a83" UNIQUE ("name"), CONSTRAINT "PK_ec39ebae82efb7cfc77302eb7b3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "data_set_review" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "data_set_id" uuid NOT NULL, "task_id" uuid NOT NULL, "reviewer_id" uuid NOT NULL, "status" character varying NOT NULL, "is_flagged" boolean NOT NULL DEFAULT false, "is_uncertain" boolean NOT NULL DEFAULT false, "expires_at" TIMESTAMP NOT NULL, "assigned_at" TIMESTAMP NOT NULL DEFAULT now(), "reviewed_at" TIMESTAMP, "score_given" integer, "is_expired" boolean NOT NULL DEFAULT false, "comment" character varying, CONSTRAINT "PK_00d5ffbcc184079c3506bb978d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rejection_reason" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reason" character varying, "rejection_type_id" uuid NOT NULL, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "data_set_id" uuid NOT NULL, "data_set_review_id" uuid NOT NULL, CONSTRAINT "PK_71de8b715b8e58e4c86486c92f6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "setting"."zone" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "alternative_names" jsonb, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "region_id" uuid NOT NULL, "deletedAt" TIMESTAMP, CONSTRAINT "UQ_d6451e19ba6b9d350327b4c4c04" UNIQUE ("name"), CONSTRAINT "PK_bd3989e5a3c3fb5ed546dfaf832" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "setting"."region" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "alternative_names" jsonb, "description" character varying, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "country_id" uuid, "deletedAt" TIMESTAMP, CONSTRAINT "UQ_8d766fc1d4d2e72ecd5f6567a02" UNIQUE ("name"), CONSTRAINT "PK_5f48ffc3af96bc486f5f3f3a6da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "setting"."country" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "alternative_names" jsonb, "code" character varying, "continent" character varying, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_2c5aa339240c0c3ae97fcc9dc4c" UNIQUE ("name"), CONSTRAINT "PK_bf6e37c231c4f4ea56dcd887269" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."data_set_status_enum" AS ENUM('Pending', 'Flagged', 'Approved', 'Rejected')`);
        await queryRunner.query(`CREATE TABLE "data_set" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying, "text_data_set" text, "status" "public"."data_set_status_enum" NOT NULL DEFAULT 'Pending', "is_draft" boolean NOT NULL DEFAULT false, "is_flagged" boolean NOT NULL DEFAULT false, "queue_status" character varying NOT NULL DEFAULT 'completed', "is_paid_for_contributor" boolean NOT NULL DEFAULT false, "is_paid_for_reviewer" boolean NOT NULL DEFAULT false, "is_test" boolean NOT NULL DEFAULT false, "audio_duration" double precision, "created_by" character varying, "updated_by" character varying, "file_path" character varying, "type" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "micro_task_id" uuid, "contributor_id" uuid NOT NULL, "dialect_id" uuid, "language_id" uuid, "qa_review_status" character varying NOT NULL DEFAULT 'Pending', CONSTRAINT "PK_180b9331dc16e4e6378217a6f61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_ip" character varying, "action_type" character varying, "action_end_point" character varying, "created_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, CONSTRAINT "PK_eca046d4b8c20d9309b35f07b69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wallet" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "balance" numeric(10,4) NOT NULL DEFAULT '0', "held_balance" numeric(10,4) NOT NULL DEFAULT '0', "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "integrity_hash" character varying, CONSTRAINT "REL_72548a47ac4a996cd254b08252" UNIQUE ("user_id"), CONSTRAINT "PK_bec464dd8d54c39c54fd32e2334" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" character varying NOT NULL, "content" character varying NOT NULL, "description" character varying, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ae4578dcaed5adff96595e61660" UNIQUE ("name"), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_distribution"."user_score" ("id" SERIAL NOT NULL, "user_id" uuid NOT NULL, "score" double precision NOT NULL DEFAULT '100', CONSTRAINT "REL_ec699039e231a0dcc9ae8cabb4" UNIQUE ("user_id"), CONSTRAINT "PK_d8c3a8d078981d6afd578a11dd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "activity_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "action" character varying NOT NULL, "entity_type" character varying, "entity_id" character varying, "metadata" character varying, "user_agent" character varying, "ip" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_f25287b6140c5ba18d38776a796" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_device_token" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "device_token" character varying NOT NULL, "device_type" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "last_used_at" TIMESTAMP DEFAULT '"2026-05-22T15:05:23.455Z"', "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_a168517a166d3a4fa4e13790442" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."transaction_type_enum" AS ENUM('Credit', 'Withdraw')`);
        await queryRunner.query(`CREATE TYPE "public"."transaction_status_enum" AS ENUM('Pending', 'Done', 'Failed')`);
        await queryRunner.query(`CREATE TABLE "transaction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" numeric(10,2) NOT NULL, "type" "public"."transaction_type_enum" NOT NULL, "metadata" jsonb, "status" "public"."transaction_status_enum" NOT NULL, "user_id" uuid NOT NULL, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_89eadb93a89810556e1cbcd6ab9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_referrals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "referrer_id" uuid NOT NULL, "referred_id" uuid NOT NULL, "max_payout_count" integer NOT NULL DEFAULT '0', "current_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6aa5154ef7ddb379082279aa87b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying, "middle_name" character varying, "last_name" character varying, "email" character varying, "phone_number" character varying, "national_id" character varying, "kyc_verification_status" character varying NOT NULL DEFAULT 'pending', "password" character varying NOT NULL, "profile_picture" character varying, "birth_date" TIMESTAMP, "gender" character varying, "is_active" boolean NOT NULL DEFAULT true, "has_logged_in" boolean NOT NULL DEFAULT false, "created_by" character varying, "updated_by" character varying, "referral_code" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "language_id" uuid, "dialect_id" uuid, "role_id" uuid NOT NULL, "woreda" character varying, "city" character varying, "zone_id" uuid, "region_id" uuid, "preferred_language" character varying DEFAULT 'en', "sectors" text array, "wallet_id" uuid, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_17d1817f241f10a3dbafb169fd2" UNIQUE ("phone_number"), CONSTRAINT "UQ_232b9597ff9a89b2c2fc5d1b5e5" UNIQUE ("national_id"), CONSTRAINT "REL_67abb81dc33e75d1743323fd5d" UNIQUE ("wallet_id"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "task_distribution"."score_log_action_enum" AS ENUM('SUBMIT', 'ACCEPT', 'REJECT')`);
        await queryRunner.query(`CREATE TABLE "task_distribution"."score_log" ("id" SERIAL NOT NULL, "action" "task_distribution"."score_log_action_enum" NOT NULL, "user_id" character varying NOT NULL, "point" double precision NOT NULL DEFAULT '0', CONSTRAINT "PK_391df523cdc37b21fdd552d0ad5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_distribution"."micro_task_statistics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "micro_task_id" character varying NOT NULL, "task_id" character varying NOT NULL, "no_of_contributors" integer NOT NULL, "expected_no_of_contributors" integer NOT NULL, "total_male" integer, "total_female" integer, "created_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aa92e4330a35ae342368de232fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "task_distribution"."contributor_micro_tasks_status_enum" AS ENUM('New', 'InProgress', 'Completed', 'Expired')`);
        await queryRunner.query(`CREATE TABLE "task_distribution"."contributor_micro_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "contributor_id" uuid NOT NULL, "gender" character varying, "task_id" uuid NOT NULL, "micro_task_ids" text array, "status" "task_distribution"."contributor_micro_tasks_status_enum" NOT NULL DEFAULT 'New', "expected_micro_task_for_contributor" integer NOT NULL, "batch" integer, "current_batch" integer NOT NULL DEFAULT '0', "total_micro_tasks" integer NOT NULL, "dead_line" TIMESTAMP, "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "created_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2ac516ff276a13e901b2131cd0f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "score_value" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "value_in_birr" integer NOT NULL, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2bf62a784c7f693165fd9989e44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contact_us" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" character varying NOT NULL, "email" character varying NOT NULL, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "phone_number" character varying NOT NULL, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b61766a4d93470109266b976cfe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "blog" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "author" character varying, "full_content" text, "image_url" character varying, "overview" text, "minutes_to_read" integer, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_85c6532ad065a448e9de7638571" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "role_id" character varying, "title" character varying NOT NULL, "message" character varying NOT NULL, "type" character varying NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "is_actionable" boolean NOT NULL DEFAULT false, "action_url" character varying, "created_by" character varying, "updated_by" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "setting"."sector" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "alternative_names" jsonb, "description" character varying, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_23e1125a0a0e6b06d3e825ba990" UNIQUE ("name"), CONSTRAINT "PK_668b2ea8a2f534425407732f3ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_verification_codes_status_enum" AS ENUM('pending', 'verified', 'expired')`);
        await queryRunner.query(`CREATE TABLE "user_verification_codes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "code" character varying NOT NULL, "expiration_date" TIMESTAMP NOT NULL, "status" "public"."user_verification_codes_status_enum" NOT NULL DEFAULT 'pending', "failed_attempts" integer NOT NULL DEFAULT '0', "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_97fbda7ca86b8e3742bd553cb9c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_score_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "action" character varying NOT NULL, "point" integer NOT NULL, "created_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197cf51b38346e715a89da5ea50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "data_set_review_annotations" ("data_set_review_id" uuid NOT NULL, "annotation_id" uuid NOT NULL, CONSTRAINT "PK_9331c61d3c12cf5bc30ba54d828" PRIMARY KEY ("data_set_review_id", "annotation_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b4bb5831a43766c703c1162486" ON "data_set_review_annotations" ("data_set_review_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f66ce7b7daa078136886455a6" ON "data_set_review_annotations" ("annotation_id") `);
        await queryRunner.query(`CREATE TABLE "role_permission" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_19a94c31d4960ded0dcd0397759" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d0a7155eafd75ddba5a701336" ON "role_permission" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3a3ba47b7ca00fd23be4ebd6c" ON "role_permission" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "invitation_link" ADD CONSTRAINT "FK_ed6e991a0f865556d93ed7f4ac5" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation_link" ADD CONSTRAINT "FK_a479291c56cbb4783a5f7fde1e8" FOREIGN KEY ("task_id") REFERENCES "task"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation_link" ADD CONSTRAINT "FK_72b5a8586f0015f16e14c9d8102" FOREIGN KEY ("organization_id") REFERENCES "setting"."organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_14a9a6e2dbe451fe6f136f440f0" FOREIGN KEY ("manager_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "setting"."dialect" ADD CONSTRAINT "FK_85a5608e77fd444dc9317f2e137" FOREIGN KEY ("language_id") REFERENCES "setting"."language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_task" ADD CONSTRAINT "FK_8c3de90b3f84f555158abb989b1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_task" ADD CONSTRAINT "FK_46d6ee5a89290d66abf7b0622a1" FOREIGN KEY ("task_id") REFERENCES "task"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_instruction" ADD CONSTRAINT "FK_01581ae3e9671770eda8de1c1b2" FOREIGN KEY ("task_id") REFERENCES "task"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_payment" ADD CONSTRAINT "FK_0c32d331e470ebb15a1c98e48ba" FOREIGN KEY ("task_id") REFERENCES "task"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_requirement" ADD CONSTRAINT "FK_62ec6ff566bc90aec40fccd9b3c" FOREIGN KEY ("task_id") REFERENCES "task"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facilitator_contributor" ADD CONSTRAINT "FK_683ea9c0387913382e856143be7" FOREIGN KEY ("facilitator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facilitator_contributor" ADD CONSTRAINT "FK_c5a822286622d74921c8782d744" FOREIGN KEY ("contributor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facilitator_contributor" ADD CONSTRAINT "FK_6746586afa5cbe6f1b8c9870619" FOREIGN KEY ("task_id") REFERENCES "task"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qa_task_instruction" ADD CONSTRAINT "FK_6bf4ff6fc0d3958861cddeb4692" FOREIGN KEY ("task_id") REFERENCES "task"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qa_task_instruction" ADD CONSTRAINT "FK_13a7f17b3cea7e095cd76f1a6f3" FOREIGN KEY ("reviewerTaskId") REFERENCES "task"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qa_task_instruction" ADD CONSTRAINT "FK_72a52596b48a8b96cacc0b7be58" FOREIGN KEY ("qaTaskId") REFERENCES "task"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviewer_task_instruction" ADD CONSTRAINT "FK_bd4f85f249b2074d3790bfaa5e0" FOREIGN KEY ("task_id") REFERENCES "task"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviewer_task_instruction" ADD CONSTRAINT "FK_439b68c589853aef207bc94b846" FOREIGN KEY ("reviewerTaskId") REFERENCES "task"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviewer_task_instruction" ADD CONSTRAINT "FK_02c82b9da96a4289b48a2038393" FOREIGN KEY ("qaTaskId") REFERENCES "task"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_1f53e7ffe94530f9e0221224d29" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_8988df3c20ed23453438fe68d83" FOREIGN KEY ("task_type_id") REFERENCES "task_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_a28b46f5e8c22aad63bcf3ad1b2" FOREIGN KEY ("language_id") REFERENCES "setting"."language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "micro_task" ADD CONSTRAINT "FK_b6e76c2e47b4001fda5f87ec5c1" FOREIGN KEY ("task_id") REFERENCES "task"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flag_reason" ADD CONSTRAINT "FK_5487cc530c4023a56775c46df44" FOREIGN KEY ("data_set_id") REFERENCES "data_set"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flag_reason" ADD CONSTRAINT "FK_f2507d6dbdf8b8f06fc585de642" FOREIGN KEY ("data_set_review_id") REFERENCES "data_set_review"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flag_reason" ADD CONSTRAINT "FK_b24b99c3237a9f08347ddf54711" FOREIGN KEY ("flag_type_id") REFERENCES "setting"."flag_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "setting"."annotation" ADD CONSTRAINT "FK_f2b33df5bba09b147f7038a65da" FOREIGN KEY ("annotation_type_id") REFERENCES "setting"."annotation_type"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_set_review" ADD CONSTRAINT "FK_c26babd1c1af946352106da305e" FOREIGN KEY ("data_set_id") REFERENCES "data_set"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_set_review" ADD CONSTRAINT "FK_fcde9c3b067d8826d7aca36b554" FOREIGN KEY ("reviewer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rejection_reason" ADD CONSTRAINT "FK_ff971d2f765c63ea082c2bbb195" FOREIGN KEY ("data_set_id") REFERENCES "data_set"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rejection_reason" ADD CONSTRAINT "FK_518d7081f8b627b884aa0227dec" FOREIGN KEY ("data_set_review_id") REFERENCES "data_set_review"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rejection_reason" ADD CONSTRAINT "FK_0d5b90f9d518f6553e2f092b065" FOREIGN KEY ("rejection_type_id") REFERENCES "setting"."rejection_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "setting"."zone" ADD CONSTRAINT "FK_689193f6148365d1a4f03dc6815" FOREIGN KEY ("region_id") REFERENCES "setting"."region"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "setting"."region" ADD CONSTRAINT "FK_26b43e0b19bc5dc2c480da151b6" FOREIGN KEY ("country_id") REFERENCES "setting"."country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_set" ADD CONSTRAINT "FK_5e3b272ff0538c1d02b70462042" FOREIGN KEY ("micro_task_id") REFERENCES "micro_task"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_set" ADD CONSTRAINT "FK_0ce1eeee1c5819c33f18b15ea8b" FOREIGN KEY ("contributor_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_set" ADD CONSTRAINT "FK_1e1551f362558f50b8a71845ecf" FOREIGN KEY ("dialect_id") REFERENCES "setting"."dialect"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_set" ADD CONSTRAINT "FK_fa5f4abe113fa753f0735587ae0" FOREIGN KEY ("language_id") REFERENCES "setting"."language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_log" ADD CONSTRAINT "FK_86d86e827a8e203ef7d390e081e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD CONSTRAINT "FK_72548a47ac4a996cd254b082522" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_distribution"."user_score" ADD CONSTRAINT "FK_ec699039e231a0dcc9ae8cabb40" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_597e6df96098895bf19d4b5ea45" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_device_token" ADD CONSTRAINT "FK_b023f64c461087cc6b29316f5a4" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "FK_b4a3d92d5dde30f3ab5c34c5862" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_referrals" ADD CONSTRAINT "FK_aa6b0c138c5176c76f6951bcb2e" FOREIGN KEY ("referrer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_referrals" ADD CONSTRAINT "FK_ebe5702f3703d832d5672c3db6c" FOREIGN KEY ("referred_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_5467acf58b481907933d4eaf046" FOREIGN KEY ("language_id") REFERENCES "setting"."language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_6e8aefd524d54c5d9616c364e11" FOREIGN KEY ("dialect_id") REFERENCES "setting"."dialect"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_31def451399d7c949d9fd2bae8a" FOREIGN KEY ("zone_id") REFERENCES "setting"."zone"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_1901e9aae03c8897b7dd460c27f" FOREIGN KEY ("region_id") REFERENCES "setting"."region"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_67abb81dc33e75d1743323fd5db" FOREIGN KEY ("wallet_id") REFERENCES "wallet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_score_log" ADD CONSTRAINT "FK_d26b381563a25d124f8c0e78f9c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_set_review_annotations" ADD CONSTRAINT "FK_b4bb5831a43766c703c11624868" FOREIGN KEY ("data_set_review_id") REFERENCES "data_set_review"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "data_set_review_annotations" ADD CONSTRAINT "FK_1f66ce7b7daa078136886455a6d" FOREIGN KEY ("annotation_id") REFERENCES "setting"."annotation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368"`);
        await queryRunner.query(`ALTER TABLE "data_set_review_annotations" DROP CONSTRAINT "FK_1f66ce7b7daa078136886455a6d"`);
        await queryRunner.query(`ALTER TABLE "data_set_review_annotations" DROP CONSTRAINT "FK_b4bb5831a43766c703c11624868"`);
        await queryRunner.query(`ALTER TABLE "user_score_log" DROP CONSTRAINT "FK_d26b381563a25d124f8c0e78f9c"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_67abb81dc33e75d1743323fd5db"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_1901e9aae03c8897b7dd460c27f"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_31def451399d7c949d9fd2bae8a"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_6e8aefd524d54c5d9616c364e11"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_5467acf58b481907933d4eaf046"`);
        await queryRunner.query(`ALTER TABLE "user_referrals" DROP CONSTRAINT "FK_ebe5702f3703d832d5672c3db6c"`);
        await queryRunner.query(`ALTER TABLE "user_referrals" DROP CONSTRAINT "FK_aa6b0c138c5176c76f6951bcb2e"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "FK_b4a3d92d5dde30f3ab5c34c5862"`);
        await queryRunner.query(`ALTER TABLE "user_device_token" DROP CONSTRAINT "FK_b023f64c461087cc6b29316f5a4"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_597e6df96098895bf19d4b5ea45"`);
        await queryRunner.query(`ALTER TABLE "task_distribution"."user_score" DROP CONSTRAINT "FK_ec699039e231a0dcc9ae8cabb40"`);
        await queryRunner.query(`ALTER TABLE "wallet" DROP CONSTRAINT "FK_72548a47ac4a996cd254b082522"`);
        await queryRunner.query(`ALTER TABLE "user_log" DROP CONSTRAINT "FK_86d86e827a8e203ef7d390e081e"`);
        await queryRunner.query(`ALTER TABLE "data_set" DROP CONSTRAINT "FK_fa5f4abe113fa753f0735587ae0"`);
        await queryRunner.query(`ALTER TABLE "data_set" DROP CONSTRAINT "FK_1e1551f362558f50b8a71845ecf"`);
        await queryRunner.query(`ALTER TABLE "data_set" DROP CONSTRAINT "FK_0ce1eeee1c5819c33f18b15ea8b"`);
        await queryRunner.query(`ALTER TABLE "data_set" DROP CONSTRAINT "FK_5e3b272ff0538c1d02b70462042"`);
        await queryRunner.query(`ALTER TABLE "setting"."region" DROP CONSTRAINT "FK_26b43e0b19bc5dc2c480da151b6"`);
        await queryRunner.query(`ALTER TABLE "setting"."zone" DROP CONSTRAINT "FK_689193f6148365d1a4f03dc6815"`);
        await queryRunner.query(`ALTER TABLE "rejection_reason" DROP CONSTRAINT "FK_0d5b90f9d518f6553e2f092b065"`);
        await queryRunner.query(`ALTER TABLE "rejection_reason" DROP CONSTRAINT "FK_518d7081f8b627b884aa0227dec"`);
        await queryRunner.query(`ALTER TABLE "rejection_reason" DROP CONSTRAINT "FK_ff971d2f765c63ea082c2bbb195"`);
        await queryRunner.query(`ALTER TABLE "data_set_review" DROP CONSTRAINT "FK_fcde9c3b067d8826d7aca36b554"`);
        await queryRunner.query(`ALTER TABLE "data_set_review" DROP CONSTRAINT "FK_c26babd1c1af946352106da305e"`);
        await queryRunner.query(`ALTER TABLE "setting"."annotation" DROP CONSTRAINT "FK_f2b33df5bba09b147f7038a65da"`);
        await queryRunner.query(`ALTER TABLE "flag_reason" DROP CONSTRAINT "FK_b24b99c3237a9f08347ddf54711"`);
        await queryRunner.query(`ALTER TABLE "flag_reason" DROP CONSTRAINT "FK_f2507d6dbdf8b8f06fc585de642"`);
        await queryRunner.query(`ALTER TABLE "flag_reason" DROP CONSTRAINT "FK_5487cc530c4023a56775c46df44"`);
        await queryRunner.query(`ALTER TABLE "micro_task" DROP CONSTRAINT "FK_b6e76c2e47b4001fda5f87ec5c1"`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_a28b46f5e8c22aad63bcf3ad1b2"`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_8988df3c20ed23453438fe68d83"`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_1f53e7ffe94530f9e0221224d29"`);
        await queryRunner.query(`ALTER TABLE "reviewer_task_instruction" DROP CONSTRAINT "FK_02c82b9da96a4289b48a2038393"`);
        await queryRunner.query(`ALTER TABLE "reviewer_task_instruction" DROP CONSTRAINT "FK_439b68c589853aef207bc94b846"`);
        await queryRunner.query(`ALTER TABLE "reviewer_task_instruction" DROP CONSTRAINT "FK_bd4f85f249b2074d3790bfaa5e0"`);
        await queryRunner.query(`ALTER TABLE "qa_task_instruction" DROP CONSTRAINT "FK_72a52596b48a8b96cacc0b7be58"`);
        await queryRunner.query(`ALTER TABLE "qa_task_instruction" DROP CONSTRAINT "FK_13a7f17b3cea7e095cd76f1a6f3"`);
        await queryRunner.query(`ALTER TABLE "qa_task_instruction" DROP CONSTRAINT "FK_6bf4ff6fc0d3958861cddeb4692"`);
        await queryRunner.query(`ALTER TABLE "facilitator_contributor" DROP CONSTRAINT "FK_6746586afa5cbe6f1b8c9870619"`);
        await queryRunner.query(`ALTER TABLE "facilitator_contributor" DROP CONSTRAINT "FK_c5a822286622d74921c8782d744"`);
        await queryRunner.query(`ALTER TABLE "facilitator_contributor" DROP CONSTRAINT "FK_683ea9c0387913382e856143be7"`);
        await queryRunner.query(`ALTER TABLE "task_requirement" DROP CONSTRAINT "FK_62ec6ff566bc90aec40fccd9b3c"`);
        await queryRunner.query(`ALTER TABLE "task_payment" DROP CONSTRAINT "FK_0c32d331e470ebb15a1c98e48ba"`);
        await queryRunner.query(`ALTER TABLE "task_instruction" DROP CONSTRAINT "FK_01581ae3e9671770eda8de1c1b2"`);
        await queryRunner.query(`ALTER TABLE "user_task" DROP CONSTRAINT "FK_46d6ee5a89290d66abf7b0622a1"`);
        await queryRunner.query(`ALTER TABLE "user_task" DROP CONSTRAINT "FK_8c3de90b3f84f555158abb989b1"`);
        await queryRunner.query(`ALTER TABLE "setting"."dialect" DROP CONSTRAINT "FK_85a5608e77fd444dc9317f2e137"`);
        await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_14a9a6e2dbe451fe6f136f440f0"`);
        await queryRunner.query(`ALTER TABLE "invitation_link" DROP CONSTRAINT "FK_72b5a8586f0015f16e14c9d8102"`);
        await queryRunner.query(`ALTER TABLE "invitation_link" DROP CONSTRAINT "FK_a479291c56cbb4783a5f7fde1e8"`);
        await queryRunner.query(`ALTER TABLE "invitation_link" DROP CONSTRAINT "FK_ed6e991a0f865556d93ed7f4ac5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3a3ba47b7ca00fd23be4ebd6c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d0a7155eafd75ddba5a701336"`);
        await queryRunner.query(`DROP TABLE "role_permission"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f66ce7b7daa078136886455a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4bb5831a43766c703c1162486"`);
        await queryRunner.query(`DROP TABLE "data_set_review_annotations"`);
        await queryRunner.query(`DROP TABLE "user_score_log"`);
        await queryRunner.query(`DROP TABLE "user_verification_codes"`);
        await queryRunner.query(`DROP TYPE "public"."user_verification_codes_status_enum"`);
        await queryRunner.query(`DROP TABLE "setting"."sector"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TABLE "blog"`);
        await queryRunner.query(`DROP TABLE "contact_us"`);
        await queryRunner.query(`DROP TABLE "score_value"`);
        await queryRunner.query(`DROP TABLE "task_distribution"."contributor_micro_tasks"`);
        await queryRunner.query(`DROP TYPE "task_distribution"."contributor_micro_tasks_status_enum"`);
        await queryRunner.query(`DROP TABLE "task_distribution"."micro_task_statistics"`);
        await queryRunner.query(`DROP TABLE "task_distribution"."score_log"`);
        await queryRunner.query(`DROP TYPE "task_distribution"."score_log_action_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "user_referrals"`);
        await queryRunner.query(`DROP TABLE "transaction"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_type_enum"`);
        await queryRunner.query(`DROP TABLE "user_device_token"`);
        await queryRunner.query(`DROP TABLE "activity_logs"`);
        await queryRunner.query(`DROP TABLE "task_distribution"."user_score"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "wallet"`);
        await queryRunner.query(`DROP TABLE "user_log"`);
        await queryRunner.query(`DROP TABLE "data_set"`);
        await queryRunner.query(`DROP TYPE "public"."data_set_status_enum"`);
        await queryRunner.query(`DROP TABLE "setting"."country"`);
        await queryRunner.query(`DROP TABLE "setting"."region"`);
        await queryRunner.query(`DROP TABLE "setting"."zone"`);
        await queryRunner.query(`DROP TABLE "rejection_reason"`);
        await queryRunner.query(`DROP TABLE "data_set_review"`);
        await queryRunner.query(`DROP TABLE "setting"."annotation"`);
        await queryRunner.query(`DROP TABLE "setting"."annotation_type"`);
        await queryRunner.query(`DROP TABLE "flag_reason"`);
        await queryRunner.query(`DROP TABLE "setting"."flag_type"`);
        await queryRunner.query(`DROP TABLE "setting"."rejection_type"`);
        await queryRunner.query(`DROP TABLE "micro_task"`);
        await queryRunner.query(`DROP TYPE "public"."micro_task_status_enum"`);
        await queryRunner.query(`DROP TABLE "task"`);
        await queryRunner.query(`DROP TABLE "reviewer_task_instruction"`);
        await queryRunner.query(`DROP TABLE "qa_task_instruction"`);
        await queryRunner.query(`DROP TABLE "facilitator_contributor"`);
        await queryRunner.query(`DROP TABLE "task_requirement"`);
        await queryRunner.query(`DROP TABLE "task_payment"`);
        await queryRunner.query(`DROP TABLE "task_instruction"`);
        await queryRunner.query(`DROP TABLE "user_task"`);
        await queryRunner.query(`DROP TYPE "public"."user_task_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_task_role_enum"`);
        await queryRunner.query(`DROP TABLE "setting"."language"`);
        await queryRunner.query(`DROP TABLE "setting"."dialect"`);
        await queryRunner.query(`DROP TABLE "task_type"`);
        await queryRunner.query(`DROP TYPE "public"."task_type_task_type_enum"`);
        await queryRunner.query(`DROP TABLE "project"`);
        await queryRunner.query(`DROP TYPE "public"."project_status_enum"`);
        await queryRunner.query(`DROP TABLE "invitation_link"`);
        await queryRunner.query(`DROP TYPE "public"."invitation_link_role_enum"`);
        await queryRunner.query(`DROP TABLE "setting"."organization"`);

        // drop the schema
    await queryRunner.query(`DROP SCHEMA IF EXISTS "setting" CASCADE`);
    await queryRunner.query(
      `DROP SCHEMA IF EXISTS "task_distribution" CASCADE`,
    );
    }

}
